# General
spring.application.name=medical-clinic

# Database
#spring.datasource.url=jdbc:h2:mem:medicalclinicdb
spring.datasource.url=jdbc:h2:mem:medicalclinicdb;DB_CLOSE_DELAY=-1;
#spring.datasource.url=jdbc:h2:file:/data/demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# for .sql files to run after hibernate (not recommended though)
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

#auto generowanie schematu?
spring.jpa.hibernate.ddl-auto=create

# Swagger (OpenApi)
springdoc.api-docs.path=/api-docs

# Logger
logging.level.root=INFO
logging.level.com.neqrofukk.medicalclinic=DEBUG